"""CoRE Stack public v2 routes this MCP server is allowed to call."""

from dataclasses import dataclass


@dataclass(frozen=True)
class PublicAPI:
    id: str
    path: str
    description: str
    parameters: tuple[str, ...]


PUBLIC_APIS: tuple[PublicAPI, ...] = (
    PublicAPI(
        "get_active_locations",
        "/api/v2/get_active_locations/",
        "States, districts, and tehsils for which CoRE Stack has generated datasets. "
        "Optional filters: state, district, tehsil.",
        ("state", "district", "tehsil"),
    ),
    PublicAPI(
        "get_admin_details_by_latlon",
        "/api/v2/get_admin_details_by_latlon/",
        "Resolve latitude and longitude to the State, District, and Tehsil names "
        "CoRE Stack uses on the other dataset APIs.",
        ("latitude", "longitude"),
    ),
    PublicAPI(
        "get_mwsid_by_latlon",
        "/api/v2/get_mwsid_by_latlon/",
        "Resolve latitude and longitude to the micro-watershed uid, plus State, "
        "District, and Tehsil. Pass uid as mws_id to the time series and report APIs.",
        ("latitude", "longitude"),
    ),
    PublicAPI(
        "get_tehsil_data",
        "/api/v2/get_tehsil_data/",
        "Datasets generated by CoRE Stack for one tehsil, one row per micro-watershed. "
        "Omit data, or pass data=all, for every dataset in that tehsil file. "
        "Pass data=drought,stream_order to keep named datasets.",
        ("state", "district", "tehsil", "data"),
    ),
    PublicAPI(
        "get_mws_data",
        "/api/v2/get_mws_data/",
        "Fortnight evapotranspiration, runoff, and precipitation for one micro-watershed. "
        "Optional fields=et,runoff,precipitation.",
        ("state", "district", "tehsil", "mws_id", "fields"),
    ),
    PublicAPI(
        "get_mws_kyl_indicators",
        "/api/v2/get_mws_kyl_indicators/",
        "Know Your Landscape indicators for one micro-watershed. Optional fields=.",
        ("state", "district", "tehsil", "mws_id", "fields"),
    ),
    PublicAPI(
        "get_generated_layer_urls",
        "/api/v2/get_generated_layer_urls/",
        "GeoServer layer URLs for one tehsil. Open layer_url in QGIS.",
        ("state", "district", "tehsil"),
    ),
    PublicAPI(
        "get_mws_report",
        "/api/v2/get_mws_report/",
        "Watershed report URL for one micro-watershed.",
        ("state", "district", "tehsil", "mws_id"),
    ),
    PublicAPI(
        "get_mws_geometries",
        "/api/v2/get_mws_geometries/",
        "Micro-watershed polygons for one tehsil, as a GeoJSON FeatureCollection.",
        ("state", "district", "tehsil"),
    ),
    PublicAPI(
        "get_village_geometries",
        "/api/v2/get_village_geometries/",
        "Village polygons for one tehsil, as a GeoJSON FeatureCollection.",
        ("state", "district", "tehsil"),
    ),
    PublicAPI(
        "get_waterbodies_data_by_admin",
        "/api/v2/get_waterbodies_data_by_admin/",
        "Waterbodies in one tehsil, detected by the CoRE Stack remote sensing method, "
        "with seasonal water availability, zone of influence, and cropping intensity.",
        ("state", "district", "tehsil"),
    ),
    PublicAPI(
        "get_waterbody_data",
        "/api/v2/get_waterbody_data/",
        "One waterbody for a tehsil and uid. Same fields as the waterbodies-by-admin API.",
        ("state", "district", "tehsil", "uid"),
    ),
)

API_BY_ID = {item.id: item for item in PUBLIC_APIS}


def public_api(api_id: str) -> PublicAPI:
    try:
        return API_BY_ID[api_id]
    except KeyError as exc:
        known = ", ".join(API_BY_ID)
        raise KeyError(f"Unknown api_id {api_id!r}. Known ids: {known}") from exc
